### ISSUE TITLE
Синий экран

### ISSUE THREAD

**Issue by koke228666** [123jjck/daisydaleplusplus#29]
![изображение](https://github.com/user-attachments/assets/6a0b0070-109f-446b-b001-f633fb291fb5)
Привет. Установил по инструкции, base.swf взял [отсюда](https://github.com/123jjck/ddplusplus/issues/14#issuecomment-907766528), использую minfs, запускаю игру через Ruffle на Firefox 133.
AMS:
![изображение](https://github.com/user-attachments/assets/87e7e741-2dcf-4d64-a3cf-8db6e068d9b3)
Консоль браузера:
![изображение](https://github.com/user-attachments/assets/ee34f25b-7c09-4580-b5af-3bb9bfa27cb4)

**Comment by 123jjck** [comment]
Привет! Ruffle не работает с Шарарамом, так как в нём ещё не реализована поддержка RTMP.
Способ завести Шарарам через Ruffle, разумеется, есть - возможно, в будущем он станет известен публике))

Пока что из вариантов поиграть на локалке - использовать браузер с флешем. У меня есть подробный гайд:
https://vk.com/@-186221588-kak-prodolzhat-igrat-vo-flash-igry-v-2024-godu

**Comment by koke228666** [comment]
@123jjck 
Спасибо, заработало. А как можно поднять фс из [oldswf.zip](https://mega.nz/file/RTgmxIpD#J6w_ZdMHKc-H5njO_kJE0iJo9nwJHOG1anKyk9MMu64)? Перерыл кучу сохранённых base.swf - грузят исключительно шифрованное хранилище младше ~2014 года

**Comment by 123jjck** [comment]
> Перерыл кучу сохранённых base.swf - грузят исключительно шифрованное хранилище младше ~2014 года

это не столь от бейза зависит, сколько от настроек [ServerAction](https://github.com/123jjck/ddplusplus/blob/master/front/ServerAction.php) - тут `RPath="fs/3p897j5lf4e0j.swf"` заменить на `RPath="swf/cache/rus/resources.swf"` и `Parameter="VersionMode" Value="2"` заменить на `Parameter="VersionMode" Value="1"`

**Comment by koke228666** [comment]
Сделал, теперь выдаёт это
![изображение](https://github.com/user-attachments/assets/734e25d8-a024-4780-804b-c054e923c221)

> `RPath="fs/3p897j5lf4e0j.swf"` заменить на `RPath="swf/cache/rus/resources.swf"` и `Parameter="VersionMode" Value="2"` заменить на `Parameter="VersionMode" Value="1"`

**Comment by 123jjck** [comment]
> теперь выдаёт это 

Какого-то из файлов не хватает в хранилище oldswf. Посмотри через инструменты разработчика (F12) во вкладке "Network" - этот файл должен несколько раз запрашиваться, а далее игра сама отключает от сервера и выводит ошибку

Насколько я помню, это файл avatar.swf. И его особенность в том, что он должен лежать в корне htdocs, а не в папке с другими свфшками (собственно, поэтому его и нет в oldswf)

Аналог этого файла в новом флеш хранилище - ек4pydl5s0lc.swf
Можешь попробовать его переименовать в avatar.swf и закинуть в htdocs
